---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

CLEAR WORKSPACE

```{r}
rm(list=ls())
```

RETRIEVE DATA

```{r}
seattleTop= read.csv("https://github.com/allisgoodrn/deliverable3/raw/main/seattleTop.csv")
```

OUR ADJACENCY MATRIX

```{r}
dim(seattleTop) #[1] 46 47
names(seattleTop)
```

MOVE COLUMN NAMES AS ROW NAMES 

```{r}
row.names(seattleTop)=seattleTop$name
seattleTop$name=NULL
dim(seattleTop) #[1] 46 46 
```

CONVERT DATAFRAME INTO MATRIX 

```{r}
seattleTop_mx=as.matrix(seattleTop)
```

CREATE A NETWORK VIA Igraph

```{r}
library(igraph)

seattleTop46=graph.adjacency(seattleTop_mx, mode="undirected", weighted=NULL)

#count of vertices (nodes)
vcount(seattleTop46) #[1] 46
#count of edges
ecount(seattleTop46) #[1] 393
```

WHAT THIS NETWORK LOOKS LIKE:

```{r}
plot.igraph(seattleTop46,
            vertex.color='yellow',
            edge.color='lightblue')

#NOTE: At the node level, all individual in this data is connected to two or more other persons. There is no-one individual that is connected to just a singular person.  
```

CONFIRM NETWORK CONNECTION

```{r}
is_connected(seattleTop46) #[1] TRUE
```

EXPLORE THE NETWORK: NODE PROPERTIES 

```{r}
graph.density(seattleTop46) #[1] 0.3797101
#Note: 0.38 is not a complete network. Meaning not a link between every pair of nodes. 

diameter(seattleTop46) #[1] 3
mean_distance(seattleTop46) #[1] 1.633816

sort(degree(seattleTop46)) # In terms of direct influence, the least connected individual is X2morrownight, two connections; and the most connected or with the most direct influene is toddbishop, 41 connections. 

sort(strength(seattleTop46))

sort(closeness(seattleTop46, normalized=TRUE)) 

#closeness is a measure of how long info takes to arrive (who hears news first). Higher values mean less centrality. #toddbishop is 0.9183673 and X2morrowknight is 0.4787234. toddbishop is in the know. 

sort(betweenness(seattleTop46)) #measures brokerage or gatekeeping potential/appromixately the numer of shortest paths btwn nodes that pass through a particular node. 

sort(eigen_centrality(seattleTop46)$vector) #measure of being well-connected connected to the well-connected. Only works with undirected networks.

neighbors(seattleTop46, v=which(V(seattleTop46)$name=="X2morrowknight")) #connected to DaveParkerSEA & MissDestructo

neighbors(seattleTop46,
          v=which(V(seattleTop46)$name=="X2morrowknight"))
#neighbors (for direct neighbors) 

ego(seattleTop46, order=2, nodes=which(V(seattleTop46)$name=="X2morrowknight")) 
#ego (for neighbors up to n neighbors away)

```

NETWORK PROPERTIES

```{r}
#diameter is the length of the longest path (in number of edges) between two nodes. 

diameter(seattleTop46, directed=FALSE, weights=NA) #[1] 3

#We can use get_diameter to identify the longest path between two nodes 
get_diameter(seattleTop46, directed=FALSE, weights=NA)

#mean_distance is the average number of edges between any two nodes in the network.
mean_distance(seattleTop46, directed=FALSE) #[1] 1.633816

#We can find each of these paths between pairs of edges with distances.
dist=distances(seattleTop46, weights=NA)
dist[1:5, 1:5]

#edge_density is the proportion of edges in the network over all possible edges that could exist.
edge_density(seattleTop46) #[1] 0.3797101

#reciprocity measures the propensity of each edge to be a mutual edge; that is, the probability that if i is connected to j, j is also connected to i.
reciprocity(seattleTop46)

#transitivity, also known as clustering coefficient, measures that probability that adjacent nodes of a network are connected. In other words, if i is connected to j, and j is connected to k, what is the probability that i is also connected to k?
transitivity(seattleTop46) #[1] 0.5504253
```

NETWORK COMMUNITIES
```{r}
components(seattleTop46)

par(mar=c(0,0,0,0)); plot(seattleTop46)

giant= decompose(seattleTop46)[[1]]

#The walktrap algorithm finds communities through a series of short random walks. 
cluster_walktrap(seattleTop46)
cluster_walktrap(seattleTop46, steps=10)

cluster_fast_greedy(seattleTop46)

cluster_edge_betweenness(seattleTop46)

cluster_infomap(seattleTop46)

cluster_label_prop(seattleTop46)

comm= cluster_infomap(giant)
modularity(comm) # modularity score

par(mar=c(0,0,0,0)); plot(comm, giant)

V(giant)$color= membership(comm)
par(mar=c(0,0,0,0)); plot(giant)

coreness(seattleTop46)

which(coreness(seattleTop46)==13) # what is the core of the network?

which(coreness(seattleTop46)==6) # what is the periphery of the network?
```

VISUALIZING NETWORK STRUCTURE 

```{r}
V(seattleTop46)$coreness= coreness(seattleTop46)
par(mfrow=c(2, 3), mar=c(0.1,0.1,1,0.1))
set.seed(123); fr = layout_with_fr(seattleTop46)
for (k in 1:6){
  V(seattleTop46)$color <- ifelse(V(seattleTop46)$coreness>=k, "orange", "grey")
  plot(seattleTop46, main=paste0(k, '-core shell'), layout=fr)
}
```

PREP FOR GGPLOT 

```{r}
library(ggplot2)

rounding=3
degr=round(degree(seattleTop46,normalized=T),rounding)
close=round(closeness(seattleTop46,normalized=T),rounding)
betw=round(betweenness(seattleTop46,normalized=T),rounding)
eigv=round(eigen_centrality (seattleTop46,scale=F)$vector,rounding)

seattleTop46_Centrality=as.data.frame(cbind(close,betw,eigv),stringsAsFactors = F)
names(seattleTop46_Centrality)=c('Closeness','Betweenness','Eigenvector')

seattleTop46_Centrality$person=row.names(seattleTop46_Centrality)
row.names(seattleTop46_Centrality)=NULL
head(seattleTop46_Centrality)


base=ggplot(seattleTop46_Centrality, aes(x=Betweenness, y=Closeness))
plot1=base+theme_classic() 
plot2=plot1+geom_text(aes(label=person,color=Eigenvector)) 

plot3=plot2+scale_colour_gradient(low = "orange", high = "black")
```

